name: xhabits
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rounded_date_picker: 0.3.0

  pull_to_refresh: ^1.5.8

  store_redirect: ^1.0.2

  url_launcher: ^5.4.2

  firebase_crashlytics: ^0.1.3

  # Dependency for circular chart
  flutter_circular_chart: ^0.1.0

  # Dependency for RXDart
  rxdart: ^0.23.1

  # Dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.3+2

  # Dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.9

  # Dependency for the Firebase Authentication
  firebase_auth: ^0.15.5+3

  # Dependency for the Flutter plugin to use the Firebase Realtime Database
  firebase_database: ^3.1.1

  # Dependency to use Firebase in web
  firebase: ^7.2.0

  flutter_facebook_login: ^3.0.0

  flutter_signin_button: ^1.0.0

  flutter_local_notifications: ^1.1.5+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # https://github:com/theyakka/fluro:
  fluro: "^1.5.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Background_image.png
    - assets/images/Logo.png
    - assets/images/icon.png
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Montserrat
      fonts:
        - asset:  fonts/Montserrat-Regular.ttf
        - asset:  fonts/Montserrat-Bold.ttf
          weight: 700
#    - family: SFProDisplay
#      fonts:
#        - asset: fonts/SFProDisplay-Black.ttf
#        - asset: fonts/SFProDisplay-Bold.ttf
#          weight: 700
#        - asset: fonts/SFProDisplay-Regular.ttf
#          weight: 400
#        - asset: fonts/SFProDisplay-Light.ttf
#        - asset: fonts/SFProDisplay-Thin.ttf
#        - asset: fonts/SFProDisplay-BlackItalic.ttf
#          weight: 300
#          style: italic